### ISSUE TITLE
Data duplication ？

### ISSUE THREAD

**Issue by tomoat** [carrot/roots-records#30]
app.coffee

``` coffee
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
js_pipeline  = require 'js-pipeline'
css_pipeline = require 'css-pipeline'
records      = require 'roots-records'
templates    = require 'client-templates'
config       = require 'roots-config'
S            = require 'underscore.string'
moment       = require 'moment'

api_url = 'http://192.168.1.22:8080/v2/'

module.exports =
  ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf', 'assets/*']

  extensions: [
    js_pipeline(files: 'assets/js/*.coffee'),
    css_pipeline(files: 'assets/css/*.styl'),
    templates(base: 'views/templates')
    records(
      test:
        file: "/data.json"
        template: "views/test.jade"
        out: (res) -> "/books/#{res.title}"
    )
  ]

  stylus:
    use: [axis(), rupture(), autoprefixer()]
    sourcemap: true

  'coffee-script':
    sourcemap: true

  jade:
    pretty: true

  locals:
    moment: moment

  #server:
  #  clean_urls: true

```

test.jade

``` jade
!= console.log(item)
!= console.log('+++++++++++++++=============')
!= console.log(item.id)
```

data.json

``` json
[
  {
    "id": 1001,
    "title": "The Great Gatsby",
    "summary": "A green light at the end of a dock symbolizes hedonic adaptation",
    "author": "Doge",
    "description": "this is a test"
  },
  {
    "id": 1002,
    "title": "The Great Gatsby2",
    "summary": "A green light at the end of a dock symbolizes hedonic adaptation",
    "author": "Doge",
    "description": "this is a test2"
  }
]
```

result:

``` bash
roots clean && roots watch                            
✓ output removed
compiling... { id: 1001,
  title: 'The Great Gatsby',
  summary: 'A green light at the end of a dock symbolizes hedonic adaptation',
  author: 'Doge',
  description: 'this is a test' }
+++++++++++++++=============
1001
{ id: 1002,
  title: 'The Great Gatsby2',
  summary: 'A green light at the end of a dock symbolizes hedonic adaptation',
  author: 'Doge',
  description: 'this is a test2' }
+++++++++++++++=============
1002
{ id: 1002,
  title: 'The Great Gatsby2',
  summary: 'A green light at the end of a dock symbolizes hedonic adaptation',
  author: 'Doge',
  description: 'this is a test2' }
+++++++++++++++=============
1002
done!
```

Results 1002 repeat cycles 2 times?

**Comment by jescalan** [comment]
Why is your output logged to the terminal? It should be written to an html file...

**Comment by tomoat** [comment]
Loop traversal in jade will go wrong

app.coffee

``` coffee
records(
      test:{
        file: "/data.json",
        template: "views/test.jade",
        out: (res) -> "/books/#{res.title}"
      },
      test2:{
        file: "/data2.json",
        template: "views/test2.jade",
        out: (res2) -> "/books2/#{res2.title}"
      }
    )
```

test.jade

``` jade
p #{item.title}
ul
  each tag in item.tags
    li= tag.name

```

test2.jade

``` jade
p #{item.title}
```

data.json

``` json
[
  {
    "id": 1001,
    "title": "The Great Gatsby",
    "summary": "A green light at the end of a dock symbolizes hedonic adaptation",
    "author": "Doge",
    "description": "this is a test",
    "tags": [
      {
        "tid": 644,
        "name": "a"
      },
      {
        "tid": 645,
        "name": "b"
      },
      {
        "tid": 646,
        "name": "c"
      }
    ]
  },
  {
    "id": 1002,
    "title": "The Great Gatsby2",
    "summary": "A green light at the end of a dock symbolizes hedonic adaptation",
    "author": "Doge",
    "description": "this is a test2",
    "tags": [
      {
        "tid": 644,
        "name": "aa"
      },
      {
        "tid": 645,
        "name": "bb"
      },
      {
        "tid": 646,
        "name": "cc"
      }
    ]
  }
]

```

data2.json

``` json
[
  {
    "id": 1003,
    "title": "The Great Gatsby3",
    "summary": "A green light at the end of a dock symbolizes hedonic adaptation",
    "author": "Doge",
    "description": "this is a test3"
  },
  {
    "id": 1004,
    "title": "The Great Gatsby4",
    "summary": "A green light at the end of a dock symbolizes hedonic adaptation",
    "author": "Doge",
    "description": "this is a test4"
  }
]

```

show result:

``` bash
roots watch                                          
compiling... [Error: TypeError: /Users/tomato/Sites/roots/app/views/test.jade:8
    6|
    7| ul
  > 8|   each tag in item.tags
    9|     li= tag.name
    10|

Cannot read property 'length' of undefined]

Potentially unhandled rejection [5] TypeError: /Users/tomato/Sites/roots/app/views/test.jade:8
    6|
    7| ul
  > 8|   each tag in item.tags
    9|     li= tag.name
    10|

Cannot read property 'length' of undefined
  at eval (<anonymous>:36:31)
  at eval (<anonymous>:67:4)
  at eval (<anonymous>:73:22)
  at res (/Users/tomato/Sites/roots/app/node_modules/jade/lib/index.js:219:38)
  at Object.exports.render (/Users/tomato/Sites/roots/app/node_modules/jade/lib/index.js:349:43)
  at /usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade/1.x.js:37:31
  at compile (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade/1.x.js:70:15)
  at Jade._render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade/1.x.js:35:14)
  at Jade.Adapter.render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapter_base.js:122:19)
  at CompilePass.compile_or_pass (/usr/local/lib/node_modules/roots/lib/compiler.js:522:27)
  at tryCatchReject (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:845:30)
  at runContinuation1 (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:804:4)
  at Fulfilled.when (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:592:4)
  at Pending.run (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:483:13)
  at Scheduler._drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:62:19)
  at Scheduler.drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:27:9)
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)
```

**Comment by tomoat** [comment]
I output logged to the terminal, You can help me ?
{ id: 1001,
  title: 'The Great Gatsby',
  summary: 'A green light at the end of a dock symbolizes hedonic adaptation',
  author: 'Doge',
  description: 'this is a test',
  tags:
   [ { tid: 644, name: 'a' },
     { tid: 645, name: 'b' },
     { tid: 646, name: 'c' } ] }
+++++++++++++++=============
1001
{ id: 1002,
  title: 'The Great Gatsby2',
  summary: 'A green light at the end of a dock symbolizes hedonic adaptation',
  author: 'Doge',
  description: 'this is a test2',
  tags:
   [ { tid: 644, name: 'aa' },
     { tid: 645, name: 'bb' },
     { tid: 646, name: 'cc' } ] }
+++++++++++++++=============
1002
{ id: 1004,
  title: 'The Great Gatsby4',
  summary: 'A green light at the end of a dock symbolizes hedonic adaptation',
  author: 'Doge',
  description: 'this is a test4' }
+++++++++++++++=============
1004

**Comment by tomoat** [comment]
## rename test.jade,test2.jade as  _test.jade, _test2.jade
